groups:
- name: MongoDb
  rules:
  - alert: MongoDbAlert
    expr: rate(mongodb_op_counters_total{type="query"}[10m]) > 0.15
    for:  5s
    labels:
      team: mongodb
    annotations:
      titulo: "Muitas consultas"
      descricao: "O {{ $labels.instance }}servidor de mongodb está com muitas consultas"


- name: WebApi
  rules:
  - alert: WebApiMuitosAcessos
    expr: sum(rate(http_requests_received_total[1m]))  by (instance) > 1
    for: 30s
    labels:
      team: webapi
    annotations:
      titulo: "Número alto de acessos"
      descricao: "{{ $labels.instance }} está com um número alto de acessos ({{ $value }}s)"