version: '3.8'
services:
  api:
    image: kubedevio/pedelogo-catalogo:v1.0.0
    ports:
      - "8080:80"
    networks:
      - pedelogo
    depends_on:
      - pedelogo-mongodb
    environment:
      Mongo__Host: "pedelogo-mongodb"
      Mongo__User: "mongouser"
      Mongo__Password: "mongopwd"
      Mongo__Port: "27017"
      Mongo__Database: "admin"


  pedelogo-mongodb:
    image: mongo:4.1
    networks:
      - pedelogo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    
  mongoexporter:
    image: fabricioveronez/mongo_exporter
    ports:
      - "9216:9216"
    depends_on:
      - pedelogo-mongodb
    networks:
      - pedelogo
    environment:
      MONGODB_URI: "mongodb://mongouser:mongopwd@pedelogo-mongodb:27017"


  prometheus:
    image: prom/prometheus:v2.44.0-rc.2
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yaml:/etc/prometheus/alerts.rules
    ports:
      - "9090:9090"
    depends_on:
      - api
    networks:
      - pedelogo

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - pedelogo

  alertmanager:
    image: prom/alertmanager:v0.21.0
    volumes:
      - ./alertmanager.yaml:/prometheus/alertmanager.yml
    command:
      - '--config.file=/prometheus/alertmanager.yml'
    ports:
      - 9093:9093
    networks:
      - pedelogo



networks:
  pedelogo:
    driver: bridge


