global:
  opsgenie_api_key: 
route:
  receiver: team-pager
  group_by: [alertname] 
  group_wait: 15s         
  group_interval: 15s    
  repeat_interval: 1m    
  routes:
  - receiver: 'team-pager'
    match:
      severity: page
receivers:
- name: team-pager
  opsgenie_configs:
  - api_key: 
    responders:
      - name: at-sre
        type: team